### ISSUE TITLE
Recursive Listing of Keys

### ISSUE THREAD

**Issue by efrecon** [yodlr/CoreGI#9]
The list of keys shows the "directories", but does not show the children or provide any way to recurse through the etcd tree.

**Comment by jareddlc** [comment]
@efrecon, yes currently the keys do not show children nodes. I am working on that feature as we speak.

**Comment by efrecon** [comment]
Thanks. I didn't meant to push you. Are you looking into editing the keys as well?

**Comment by jareddlc** [comment]
@efrecon yes but Im not working on that feature just quiet yet. I've listed some features in the README that we will be adding, but not limited to.

**Comment by rosskukulinski** [comment]
@efrecon we'd also welcome contributions if you have time to spare :wink:

**Comment by jareddlc** [comment]
@efrecon merged recursive listing of etcd keys. The automated docker build should be ready soon.
